import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "./Header.module.css";

const Header = () => {
  return (
    <>
      <Head>
        <title>MEIN MINER</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <header className={styles.header}>
        <div className="container">
          <div className={styles.desktop}>
            <Link href="/">
              <Image src="Logo.svg" alt="Логотип" width={180} height={44} />
            </Link>
            <div className={styles.wrapper}>
              <nav className={styles.nav}>
                <ul>
                  <li>
                    <Link href="/">Главная</Link>
                  </li>
                  <li>
                    <Link href="#">Продукты</Link>
                  </li>
                  <li>
                    <Link href="/blog">Блог</Link>
                  </li>
                  <li>
                    <Link href="#">Контакты</Link>
                  </li>
                </ul>
              </nav>
              <div className={styles.links}>
                <Link href="#">
                  <Image
                    src="telegramm.svg"
                    alt="Логотип"
                    width={24}
                    height={24}
                  />
                </Link>
                <Link href="#">
                  <Image
                    src="github.svg"
                    alt="Логотип"
                    width={24}
                    height={24}
                  />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </header>
    </>
  );
};

export default Header;
